name: CI

on:
  push:
    branches:
      - {{ cookiecutter.default_branch }}
  pull_request:
    branches:
      - {{ cookiecutter.default_branch }}

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test {{ cookiecutter.project_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1
      - name: Run {{ cookiecutter.project_name }}
        uses: ./
