name: {{ cookiecutter.action_name }}
description: {{ cookiecutter.project_short_description }}
author: {{ cookiecutter.github_username }}
inputs:
  token:
    description: 'GITHUB_TOKEN or a Repo scoped PAT'
    required: true
    default: ${{ github.token }}

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.token }}
branding:
  icon: {{ cookiecutter.action_icon }}
  color: {{ cookiecutter.action_color }}
