name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test test-project
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1
      - name: Run test-project
        uses: ./
